/**
 * Elevation lookup for real peak waypoints, keyed by exact waypoint name (as parsed by
 * lib/gpxStructure.ts). Source: Mapbox Terrain-RGB (DEM-derived, ~30m source resolution —
 * accurate to roughly +/-10-15m, not survey-grade). See docs/TOPO_REFERENCE.md.
 *
 * Generated by scripts/fetch-peak-elevations.ts (npm run elevations:fetch) — re-run that
 * script rather than hand-editing this file if the trail's waypoint set changes.
 */
export const GPX_PEAK_ELEVATIONS_M: Record<string, number> = {
  "Mingan Summit": 1885,
  "Tabag Summit": 1202,
  "Anacuao Summit": 1821,
  "Palanan Summit": 1205,
  "Cresta Summit": 1537,
  "Cetaceo Summit": 1637,
  "Cagua Summit": 1018,
  "Tapha Summit": 750,
  "Pasmacanan Summit": 422,
  "Binangonan Summit": 1065,
  "Palakong Simbahan Summit": 997,
  "Susong Dalaga Summit": 831,
  "Binuang Summit": 1068,
  "Peak 1082": 848,
  "Otundo Summit": 1452,
  "Dabukid Summit": 843,
};

export function getPeakElevationM(waypointName: string): number | null {
  return GPX_PEAK_ELEVATIONS_M[waypointName] ?? null;
}
