/**
 * One-time (re-runnable) script: fetches real elevation for every `peak`-role waypoint in
 * the authoritative GPX file from Mapbox's Terrain-RGB tileset (DEM-derived, ~30m source
 * resolution) and regenerates lib/gpxPeakElevations.ts.
 *
 * Not called at runtime — peak elevation is static reference data, so this stays a dev-time
 * script rather than adding a Mapbox API call to the request path. Re-run whenever the
 * trail's waypoint set changes.
 *
 * Usage: npm run elevations:fetch
 */
import fs from "fs";
import path from "path";
import { PNG } from "pngjs";
import { analyzeGpx } from "../lib/gpxStructure";

const ZOOM = 14;
const TILE_SIZE = 256;

function readMapboxToken(): string {
  const envPath = path.join(process.cwd(), ".env");
  const envLocalPath = path.join(process.cwd(), ".env.local");
  for (const p of [envLocalPath, envPath]) {
    if (!fs.existsSync(p)) continue;
    const match = fs.readFileSync(p, "utf-8").match(/NEXT_PUBLIC_MAPBOX_TOKEN=(.+)/);
    if (match?.[1]) return match[1].trim();
  }
  console.error("NEXT_PUBLIC_MAPBOX_TOKEN not found in .env or .env.local");
  process.exit(1);
}

/** Standard Web Mercator slippy-map tile math: lng/lat -> tile x/y + exact pixel offset within it. */
function lngLatToTilePixel(lng: number, lat: number, zoom: number) {
  const n = Math.pow(2, zoom);
  const latRad = (lat * Math.PI) / 180;
  const xFloat = ((lng + 180) / 360) * n;
  const yFloat =
    ((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2) * n;

  const tileX = Math.floor(xFloat);
  const tileY = Math.floor(yFloat);
  const pixelX = Math.floor((xFloat - tileX) * TILE_SIZE);
  const pixelY = Math.floor((yFloat - tileY) * TILE_SIZE);
  return { tileX, tileY, pixelX, pixelY };
}

/** Mapbox's documented Terrain-RGB decode formula. */
function rgbToElevationM(r: number, g: number, b: number): number {
  return -10000 + (r * 65536 + g * 256 + b) * 0.1;
}

async function fetchElevationM(lng: number, lat: number, token: string): Promise<number> {
  const { tileX, tileY, pixelX, pixelY } = lngLatToTilePixel(lng, lat, ZOOM);
  const url = `https://api.mapbox.com/v4/mapbox.terrain-rgb/${ZOOM}/${tileX}/${tileY}.pngraw?access_token=${token}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Terrain-RGB fetch failed: ${res.status} ${res.statusText}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const png = PNG.sync.read(buffer);
  const idx = (pixelY * png.width + pixelX) * 4;
  const [r, g, b] = [png.data[idx]!, png.data[idx + 1]!, png.data[idx + 2]!];
  return Math.round(rgbToElevationM(r, g, b));
}

async function main() {
  const token = readMapboxToken();
  const gpxPath = path.join(process.cwd(), "lib", "data", "The-Sierra-Madre-Nature-Trail.gpx");
  const xml = fs.readFileSync(gpxPath, "utf-8");
  const analysis = analyzeGpx(xml);
  const peaks = analysis.waypoints.filter((w) => w.role === "peak");

  console.log(`Fetching elevation for ${peaks.length} peaks from Mapbox Terrain-RGB (z${ZOOM})...\n`);

  const results: { name: string; elevation_m: number }[] = [];
  const failures: string[] = [];

  for (const peak of peaks) {
    const [lng, lat] = peak.coordinates;
    try {
      const elevation_m = await fetchElevationM(lng, lat, token);
      results.push({ name: peak.name, elevation_m });
      console.log(`  ${peak.name.padEnd(30)} ${elevation_m} m`);
    } catch (err) {
      failures.push(peak.name);
      console.error(`  ${peak.name.padEnd(30)} FAILED: ${(err as Error).message}`);
    }
  }

  if (failures.length > 0) {
    console.error(`\n${failures.length} peak(s) failed — not written to the lookup table:`);
    for (const name of failures) console.error(`  - ${name}`);
  }

  const entries = results
    .map((r) => `  "${r.name}": ${r.elevation_m},`)
    .join("\n");

  const fileContent = `/**
 * Elevation lookup for real peak waypoints, keyed by exact waypoint name (as parsed by
 * lib/gpxStructure.ts). Source: Mapbox Terrain-RGB (DEM-derived, ~30m source resolution —
 * accurate to roughly +/-10-15m, not survey-grade). See docs/TOPO_REFERENCE.md.
 *
 * Generated by scripts/fetch-peak-elevations.ts (npm run elevations:fetch) — re-run that
 * script rather than hand-editing this file if the trail's waypoint set changes.
 */
export const GPX_PEAK_ELEVATIONS_M: Record<string, number> = {
${entries}
};

export function getPeakElevationM(waypointName: string): number | null {
  return GPX_PEAK_ELEVATIONS_M[waypointName] ?? null;
}
`;

  const outPath = path.join(process.cwd(), "lib", "gpxPeakElevations.ts");
  fs.writeFileSync(outPath, fileContent, "utf-8");
  console.log(`\nWrote ${results.length} elevations to lib/gpxPeakElevations.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
